id: "xandry12_AdaptiveRagGenerator_ollama_default"
name: "Adaptive RAG using Ollama"
description: "RAG using Ollama's big local model Gemma3:12b. It supports history between messages."
class_name: "AdaptiveRagGenerator"
params:
  model_type: "OLLAMA"
  model_name: "gemma3:12b"
  temperature: 0.0
  search_type : "hybrid"
  alpha: 0.5
  chunk_limit: 5
  qt_strategy : 
  max_retries : 3
  web_search_enabled : False